package root

import (
	"fmt"
	"strings"
)

// recordRMN appends the Root Machine Notation line generated by an action.
// round/phase are the values at the moment the action was taken: the action may
// end a phase or a round, and the line must describe when it happened, not the
// resulting state.
func (g *Game) recordRMN(a Action, round int, phase string) {
	line := g.rmnLine(a, round, phase)
	if line == "" {
		return
	}
	g.RMNLog = append(g.RMNLog, line)
	if len(g.RMNLog) > 2000 {
		g.RMNLog = g.RMNLog[len(g.RMNLog)-2000:]
	}
}

func (g *Game) rmnLine(a Action, round int, phase string) string {
	actor := a.Faction
	if actor == "" {
		actor = g.Current
	}
	intent, operands := g.rmnIntent(a)
	// Record drawn cards only on the draw intent: other intents (pass, setup)
	// may draw as a side effect, and leaking hidden cards through them would be
	// wrong. Redact scrubs draw lines for opponents.
	if intent == "draw" && len(g.DrawnThisAction) > 0 {
		out := fmt.Sprintf("-> {drawn=[%s]}", strings.Join(g.DrawnThisAction, ","))
		if operands != "" {
			operands += " "
		}
		operands += out
	}
	line := fmt.Sprintf("%d %d.%s %s %s", len(g.RMNLog)+1, round, phase, actor, intent)
	if operands != "" {
		line += " " + operands
	}
	return line
}

func rmnBuilding(t string) string {
	switch t {
	case "sawmill":
		return "saw"
	case "base-fox", "base-rabbit", "base-mouse":
		return t
	}
	return t
}

func rmnWarrior(f Faction, qty int) string {
	if qty > 1 {
		return fmt.Sprintf("%d%s.w", qty, f)
	}
	return string(f) + ".w"
}

func (g *Game) rmnIntent(a Action) (string, string) {
	f := a.Faction
	if f == "" {
		f = g.Current
	}
	switch a.Kind {
	case "pass":
		return "pass", ""
	case "move":
		return "move", fmt.Sprintf("group=%s from=%s to=%s", rmnWarrior(f, a.Amount), a.From, a.To)
	case "battle":
		op := fmt.Sprintf("attacker=%s defender=%s at=%s", f, a.Target, a.Clearing)
		if g.Battle != nil && (g.Battle.D1 != 0 || g.Battle.D2 != 0) {
			op += fmt.Sprintf(" -> {atk=%d,def=%d}", g.Battle.D1, g.Battle.D2)
		}
		return "battle", op
	case "craft":
		produce := ""
		if c, ok := Card(a.Card); ok {
			if c.Item != "" {
				produce = "i." + c.Item
			} else {
				produce = "card:" + a.Card
			}
		}
		return "craft", fmt.Sprintf("who=%s card=%s produce=%s", f, a.Card, produce)
	case "spend-bird":
		return "spend-bird", fmt.Sprintf("who=%s card=%s", f, a.Card)
	case "dominance":
		return "play-dominance", fmt.Sprintf("who=%s card=%s", f, a.Card)
	case "discard":
		return "discard", fmt.Sprintf("who=%s cards=%s", f, a.Card)
	case "mc-done-crafting":
		return "notify", fmt.Sprintf("who=%s text=\"done crafting\"", f)
	case "mc-recruit":
		var cs []string
		for _, c := range g.clearingsSorted() {
			if g.buildingsOf(MC, c, "recruiter") > 0 {
				cs = append(cs, c)
			}
		}
		return "C:recruit", fmt.Sprintf("who=MC at=[%s]", strings.Join(cs, ","))
	case "mc-build":
		return "C:build", fmt.Sprintf("who=MC building=MC.b.%s at=%s", rmnBuilding(a.Building), a.Clearing)
	case "mc-overwork":
		return "C:overwork", fmt.Sprintf("at=%s spend=%s produce=MC.t.wood", a.Clearing, a.Card)
	case "decree-add":
		return "E:decree-add", fmt.Sprintf("column=%s cards=%s", strings.ToUpper(a.Column), a.Card)
	case "decree-recruit":
		return "E:recruit", fmt.Sprintf("at=[%s] card=%s", a.Clearing, a.Card)
	case "decree-move":
		return "E:move", fmt.Sprintf("group=%s from=%s to=%s card=%s", rmnWarrior(ED, a.Amount), a.From, a.To, a.Card)
	case "decree-battle":
		return "E:battle", fmt.Sprintf("defender=%s at=%s card=%s", a.Target, a.Clearing, a.Card)
	case "decree-build":
		return "E:build", fmt.Sprintf("building=ED.b.roost at=%s card=%s", a.Clearing, a.Card)
	case "ed-done-crafting":
		return "notify", "who=ED text=\"done crafting\""
	case "ed-turmoil":
		return "E:turmoil", "reason=unable"
	case "leader":
		return "E:appoint-leader", "leader=ED.ldr." + a.Leader
	case "revolt":
		suit := "fox"
		if cl := g.Clearings[a.Clearing]; cl != nil {
			suit = strings.ToLower(string(cl.Suit))
		}
		return "A:revolt", fmt.Sprintf("at=%s base=A.b.base-%s cards=%s", a.Clearing, suit, rmnCards(a.Cards))
	case "spread":
		return "A:place-sympathy", fmt.Sprintf("at=%s spend=%s", a.Clearing, rmnCards(a.Cards))
	case "mobilize":
		return "A:mobilize", fmt.Sprintf("cards=%s", a.Card)
	case "train":
		return "A:train", fmt.Sprintf("card=%s", a.Card)
	case "organize":
		return "A:organize", fmt.Sprintf("at=%s", a.Clearing)
	case "wa-recruit":
		return "place", fmt.Sprintf("group=WA.w to=%s", a.Clearing)
	case "vb-slip":
		return "V:move-pawn", fmt.Sprintf("to=%s", a.To)
	case "vb-move":
		return "move", fmt.Sprintf("group=VB.p to=%s", a.To)
	case "vb-explore":
		return "V:explore", fmt.Sprintf("at=%s", a.Clearing)
	case "vb-aid":
		take := "none"
		if a.Item != "" {
			take = "i." + a.Item
		}
		return "V:aid", fmt.Sprintf("target=%s card=%s take=%s", a.Target, a.Card, take)
	case "vb-quest":
		return "V:complete-quest", fmt.Sprintf("quest=%s reward=%s", a.Quest, a.Item)
	case "vb-repair":
		return "V:repair", fmt.Sprintf("items=%s", a.Item)
	case "vb-strike":
		return "V:strike", fmt.Sprintf("target=%s at=%s", a.Target, a.Clearing)
	case "vb-special":
		return "notify", fmt.Sprintf("who=VB text=\"special action %s\"", g.Players[VB].Character)
	case "coalition":
		return "V:coalition", fmt.Sprintf("target=%s", a.Target)
	case "battle-ambush", "battle-foil":
		cl := ""
		if g.Battle != nil {
			cl = g.Battle.Clearing
		}
		return "ambush", fmt.Sprintf("who=%s at=%s card=%s", f, cl, a.Card)
	case "battle-effect":
		return "CARD:effect", fmt.Sprintf("who=%s card=%s", f, a.Card)
	case "battle-hit":
		// The Vagabond takes hits by damaging an item; the action has no piece
		// type, only the item id.
		if a.Piece == "" && a.Item != "" {
			return "V:damage", fmt.Sprintf("items=%s", a.Item)
		}
		cl := a.Clearing
		if g.Battle != nil {
			cl = g.Battle.Clearing
		}
		switch a.Piece {
		case "warrior":
			return "remove", fmt.Sprintf("group=%s at=%s", rmnWarrior(f, 1), cl)
		case "building":
			if a.Building != "" {
				return "remove", fmt.Sprintf("group=%s.b.%s at=%s", f, rmnBuilding(a.Building), cl)
			}
		case "token":
			if a.Item != "" {
				return "remove", fmt.Sprintf("group=%s.t.%s at=%s", f, a.Item, cl)
			}
		}
		return "remove", fmt.Sprintf("group=%s at=%s", a.Piece, cl)
	case "battle-skip":
		return "notify", "text=\"skip\""
	case "field-hospitals":
		return "field-hospitals", fmt.Sprintf("at=%s spend=%s to=%s", a.Clearing, a.Card, g.Players[MC].KeepClearing)
	case "take-dominance":
		return "notify", fmt.Sprintf("who=%s text=\"took available %s spending %s\"", f, a.Item, a.Card)
	case "royal-claim":
		return "score", fmt.Sprintf("who=%s amount=%d", f, countRuled(g, f))
	case "stand-deliver":
		return "give", fmt.Sprintf("from=%s to=%s cards=?", a.Target, f)
	case "tax-collector":
		return "draw", fmt.Sprintf("who=%s qty=1 from=DECK", f)
	case "codebreakers":
		return "notify", fmt.Sprintf("who=%s text=\"looked at %s hand\"", f, a.Target)
	}
	if strings.HasPrefix(a.Kind, "setup-") {
		return setupIntent(a)
	}
	return "notify", fmt.Sprintf("text=\"%s\"", a.Kind)
}

// setupIntent renders a setup action's RMN intent. Before this, every setup
// step logged an identical "place group=? to=X", which made a replay
// undecidable — the whole point of RMN is that a log reconstructs the game
// exactly. Each setup choice now names the piece (or leader/character) it
// placed, so replay is deterministic.
func setupIntent(a Action) (string, string) {
	switch a.Kind {
	case "setup-mc-keep":
		return "place", fmt.Sprintf("group=MC.b.keep#1 to=%s", a.Clearing)
	case "setup-mc-build":
		return "place", fmt.Sprintf("group=MC.b.%s#1 to=%s", rmnBuilding(a.Building), a.Clearing)
	case "setup-ed-corner":
		return "place", fmt.Sprintf("group=(ED.b.roost#1+6ED.w) to=%s", a.Clearing)
	case "setup-ed-leader":
		return "E:appoint-leader", "leader=ED.ldr." + a.Leader
	case "setup-vb-character":
		return "V:choose-character", "character=V.character." + a.Character
	case "setup-vb-forest":
		return "V:move-pawn", fmt.Sprintf("to=%s", a.To)
	}
	return "place", fmt.Sprintf("group=? to=%s", a.Clearing)
}

// rmnCards renders a card list as an RMN unit-group.
func rmnCards(cards []string) string {
	switch len(cards) {
	case 0:
		return "?"
	case 1:
		return cards[0]
	}
	return "(" + strings.Join(cards, "+") + ")"
}

func countRuled(g *Game, f Faction) int {
	n := 0
	for c := range g.Clearings {
		if g.Rules(f, c) {
			n++
		}
	}
	return n
}
